apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-express
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-express
  local:
    path: /home/jeff/volumes/express #dossier mkdir précédent
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sd-118706 #kubectl get nodes
